---
- name: create sequence number list for hello openshift
  set_fact:
    numb_list: "{{ (numb_list | default([])) + [item] }}"
  with_sequence: "start=0 count=10"
  no_log: true

- name: create pod list
  set_fact:
    pods: "{{ (pods | default([])) + [pod_template] }}"
  no_log: true
  with_nested:
    - "{{ numb_list }}"
    - [ { svc: "http" } ]

- name: copy build templates
  template:
    src: "{{ item.src }}"
    dest: "{{ mktemp.stdout }}/templates/{{ item.dest }}"
    mode: 0777
  with_items:
    - { src: 'hello-openshift.j2', dest: 'hello-openshift.yml' }

- name: deploy hello openshift pods
  command: oc create -f {{ mktemp.stdout }}/templates/hello-openshift.yml -n test --config={{ mktemp.stdout }}/admin.kubeconfig
  register: deploy_hello
  failed_when: ('already exists' not in deploy_hello.stderr) and ('created' not in deploy_hello.stdout)
  changed_when: ('created' in deploy_hello.stdout)

- name: check if all pods are running
  shell: oc get pods -l app={{ item.name }} -n test --config={{ mktemp.stdout }}/admin.kubeconfig | tail -n1 | awk '{ print $3 }' | tail -n1
  register: check
  until: check.stdout.find("Running") != -1
  with_items:
    - "{{ pods }}"
  retries: 10
  delay: 20

- name: get hello openshift pod hostnames
  command: oc get route -n test -o json --config={{ mktemp.stdout }}/admin.kubeconfig
  register: check_route

- name: convert check_route string to json
  set_fact: check_route_json="{{ check_route.stdout | from_json }}"

- name: set query to get pod hostname
  set_fact:
    hostname_query: "items[*].spec.host"

- name: get hostname list
  set_fact:
    pod_hostnames: "{{ check_route_json | json_query(hostname_query) }}"

- name: connect to route via curl
  command: "curl -v http://{{ item }}/"
  with_items: "{{ pod_hostnames }}"
  register: check_http_route

- name: set json query
  set_fact:
    route_query: "[*].stdout"

- name: show route http response
  debug:
    msg: "{{ check_http_route.results | json_query(route_query) }}"

- name: trigger new build
  command: oc start-build hello-build -n test --config={{ mktemp.stdout }}/admin.kubeconfig
  register: build
  failed_when: ('started' not in build.stdout)
  changed_when: ('started' in build.stdout)

- name: check new build is created
  shell: oc get build --config={{ mktemp.stdout }}/admin.kubeconfig -n test | tail -n1 | awk '{ print $1 }' | tail -n1
  register: build_check
  failed_when: ('hello-build-2' not in build_check.stdout)
  changed_when: ('hello-build-2' in build_check.stdout)

- name: check if all pods with new build are running
  shell: oc get pods -l deployment={{ item.name }}-2 -n test --config={{ mktemp.stdout }}/admin.kubeconfig | tail -n1 | awk '{ print $3 }' | tail -n1
  register: check
  until: check.stdout.find("Running") != -1
  with_items: "{{ pods }}"
  retries: 10
  delay: 20

- name: connect to route via curl
  command: "curl -v http://{{ item }}/"
  with_items: "{{ pod_hostnames }}"
  register: check_http_route

- name: show route http response
  debug:
    msg: "{{ check_http_route.results | json_query(route_query) }}"
