---

- name: Check if EPEL repo is already configured.
  stat: path=/etc/yum.repos.d/epel.repo
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present
  register: result
  until: 'result.rc == 0'
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  register: result
  retries: 5
  delay: 2
  until: result.rc == 0
  with_items:
    - "wget"
    - "git"
    - "net-tools"
    - "yum-utils"
    - "bind-utils"
    - "iptables-services"
    - "bridge-utils"
    - "bash-completion"
    - "httpd-tools"

- name: enable rhel server extras
  shell: yum-config-manager --enable rhui-REGION-rhel-server-extras

- name: ensure firewalld is stopped
  service:
    name: firewalld
    state: stopped
    enabled: false
  ignore_errors: true

- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  register: result
  retries: 5
  delay: 2
  until: result.rc == 0
  with_items:
    - "docker"
    - "NetworkManager"

- name: ensure that services are started
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "docker"
    - "NetworkManager"

- name: create folders for pvs
  shell: {{ item }}
  with_items:
    - "mkdir -p /var/lib/ocp_storage/pv/pv0{1..5}"
    - "chmod -R 777 /var/lib/ocp_storage/pv/pv*"
    - "chmod -R a+w /var/lib/ocp_storage/pv/pv*"

- name: patch servers
  yum: name=* state=latest

- name: reboot servers
  shell: sleep 3 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for servers to come back
  become: false
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    port: 22
    delay: 30
    timeout: 1000
    connect_timeout: 15
  delegate_to: localhost
